### ISSUE TITLE
Rename request :)

### ISSUE THREAD

**Issue by dsyme** [CSBiology/FSharpAux#2]
Hi @muehlhaus et al,

Could I request that the name of this repo be adjusted?  e.g. FSharp.Care to FSharp.Utilities.Care or some other second-level qualification?  

Generally we always try to avoid polluting the "second level" FSharp.* namespace for F#, and instead at least qualify by a normal-looking second name.

This is covered in various discussions about package naming in the F# community, e.g. http://fsharp.github.io/2014/09/19/fsharp-libraries.html

Thanks
Don Syme

**Comment by muehlhaus** [comment]
Hello Don Syme,
thank you for pointing me to the package naming convention. It makes perfectly sense. Therefore I removed this project out of the FSharp namespace and named it FSharpAux.

Regards,
Timo Mühlhaus

**Comment by dsyme** [comment]
Supers, thanks
